language: c
compiler:
  - gcc
  - clang
before_script:
  - sudo add-apt-repository ppa:linuxjedi/ppa -y  # libuv-dev
  - sudo add-apt-repository ppa:bitshifternz/ppa -y  # premake4
  - sudo apt-get update -qq
  - sudo apt-get install premake4 libuv-dev check -y
  - make clean
script: make config=release test
branches:
  only:
    - master
    - develop
